# Generated by Django 4.1 on 2023-11-01 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('roll_number', models.CharField(error_messages={'blank': 'Roll number cannot be empty.', 'null': 'Roll number cannot be empty.', 'unique': 'This roll number already exists.'}, max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Roll number must be exactly 8 digits.', regex='^\\d{8}$')])),
                ('phone_number', models.CharField(error_messages={'blank': 'Phone number cannot be empty.', 'null': 'Phone number cannot be null.', 'unique': 'This phone number is already in use.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('branch', models.CharField(choices=[('APD', 'Architecture, Planning and Design'), ('CER', 'Ceramic Engineering and Technology'), ('CHE', 'Chemical Engineering'), ('CIV', 'Civil Engineering'), ('CSE', 'Computer Science and Engineering'), ('EEE', 'Electrical Engineering'), ('ECE', 'Electronics Engineering'), ('MEC', 'Mechanical Engineering'), ('MET', 'Metallurgical Engineering'), ('MIN', 'Mining Engineering'), ('PHE', 'Pharmaceutical Engineering and Technology'), ('IC', 'Chemistry'), ('MAT', 'Mathematical Sciences'), ('EP', 'Physics'), ('BCE', 'Biochemical Engineering'), ('BME', 'Biomedical Engineering'), ('SMST', 'Materials Science and Technology')], max_length=32)),
                ('degree', models.CharField(choices=[('Btech', 'B. Tech.'), ('Mtech', 'M. Tech.'), ('IDD', 'IDD')], max_length=5)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('TPR', 'TPR'), ('TPV', 'TPV'), ('CORE', 'Core'), ('DUTY', 'Duty'), ('VENUE', 'Venue'), ('SCHEDULING', 'Scheduling'), ('PORTAL', 'Portal')], default='STUDENT', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
