# Generated by Django 4.2.4 on 2023-11-03 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_alter_duty_tpc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='spoc_id',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'STUDENT'), _negated=True), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
