# Generated by Django 4.1 on 2023-11-01 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_id', models.AutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('round_start', models.DateTimeField(blank=True, null=True)),
                ('round_end', models.DateTimeField(blank=True, null=True)),
                ('room_no', models.CharField(default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('CLR', 'Cleared'), ('AWR', 'Awaiting Result'), ('NC', 'Not Cleared'), ('NS', 'Not Started'), ('O', 'Ongoing')], default='NS', max_length=3)),
                ('shortlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.shortlist')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
